name: example
description: Demonstrates how to use the time_picker_spinner_pop_up_dialog package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


  time_picker_spinner_pop_up_dialog:
    path: ../

flutter:
  uses-material-design: true

