name: time_picker_spinner_pop_up_dialog
description: A package show popup anchor for pick date time by using spinner cupertino style
version: 1.0.0
homepage: https://github.com/Buddybet-Group/time_picker_spinner_pop_up

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
